NOTE: update this with your service name
service: talent-ms


useDotenv: true

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'ms'}
  region: ${opt:region, 'us-east-1'}
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  environment:
    ENV: ${env:ENV}
    MONGO_URL: ${env:MONGO_URL}
    LOG_LEVEL: ${env:LOG_LEVEL}
    LOG_NAME: ${env:LOG_NAME}
    LOG_TRANSPORT: ${env:LOG_TRANSPORT}

functions:
  main: # The name of the lambda function
    # The module 'handler' is exported in the file 'src/lambda'
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'